[build]
  command = "cd client && npm install && npm run build && cd ../server-node && npm install"
  publish = "client/build"
  functions = "server-node"

[dev]
  command = "cd client && npm start"
  port = 3000
  targetPort = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-install-core" 